import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PageSidebar, PageTopMenu } from "./ui-implementations";
import { ThemeProvider } from "./provider/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div>
            <PageTopMenu />

            <div className="border-t">
              <div className="bg-background">
                <div className="grid lg:grid-cols-5">
                  <PageSidebar />

                  <div className="col-span-3 lg:col-span-4 lg:border-l">
                    <div className="h-full px-4 py-6 lg:px-8">{children}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
