import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PageSidebar, PageTopMenu } from "./ui-implementations";
import { ThemeProvider } from "./provider/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
