name: Cypress Tests

on: push

jobs:
  # job that starts the docker compose (starts the postgres database)
  # and waits for the app to be ready
  cypress-run:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: connect to postgres
        run: |
          bash prisma/scripts/init-task.sh
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: db

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run e2e:headless
          wait-on: http://localhost:3000
          wait-on-timeout: 120

  # cypress-run:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v5
  #       with:
  #         build: npm run build
  #         start: npm run e2e:headless
